---
DISABLE_LINTERS:
  [
    MARKDOWN_MARKDOWN_LINK_CHECK,
    MARKDOWN_MARKDOWN_TABLE_FORMATTER,
    SPELL_CSPELL,
    SPELL_PROSELINT,
  ]
GITHUB_STATUS_REPORTER: false
PRINT_ALPACA: false
YAML_PRETTIER_FILE_EXTENSIONS: [.yml, .md]
