---
name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: fish {0}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash
        run: >
          sudo apt-add-repository --yes --no-update ppa:fish-shell/release-3 &&
          sudo apt-get update -qq &&
          sudo apt-get install --yes
          curl
          fish
          git
          python3
          python3-venv

      - name: Install Tide unattended
        run: |
          source "$GITHUB_WORKSPACE/tools/tide_install.fish"
          tide_install --local --unattended "$GITHUB_WORKSPACE"

      - run: tide test --install

      - run: tide test --all --CI

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actionsx/prettier@v2
        with:
          args: --check .

  super-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
