name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: fish {0}

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash
        run: sudo apt-get install -y fish curl git

      - name: Install Tide unattended
        run: source "$GITHUB_WORKSPACE/tools/tide_install.fish" && tide_install -lu "$GITHUB_WORKSPACE"

      - name: Install testing dependencies
        run: sudo apt-get install -y python3 python3-venv

      - name: Install fisher and fishtape
        run: tide test -i

      - name: Run all tests
        run: tide test -a
